# Generated by Django 3.2.16 on 2023-05-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='state',
        ),
        migrations.AddField(
            model_name='state',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.theme'),
        ),
    ]
